/*
 * Launa Bucher-Austin
 * This program will act as a binary/decimal and hexdecimal/decimal convertor
 * May 2020
 */

/**
 *
 * @author launa
 */
public class binaryhexfrm extends javax.swing.JFrame {

    /**
     * Creates new form binaryhexfrm
     */
    public binaryhexfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        binttl = new javax.swing.JLabel();
        declbl = new javax.swing.JLabel();
        binlbl = new javax.swing.JLabel();
        dectxt = new javax.swing.JTextField();
        bintxt = new javax.swing.JTextField();
        decbtn = new javax.swing.JButton();
        binbtn = new javax.swing.JButton();
        decfinlbl = new javax.swing.JLabel();
        binfinlbl = new javax.swing.JLabel();
        hexttl = new javax.swing.JLabel();
        decilbl = new javax.swing.JLabel();
        hexlbl = new javax.swing.JLabel();
        decitxt = new javax.swing.JTextField();
        hextxt = new javax.swing.JTextField();
        decibtn = new javax.swing.JButton();
        hexbtn = new javax.swing.JButton();
        decifinlbl = new javax.swing.JLabel();
        hexfinlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        binttl.setText("Decimal and Binary");

        declbl.setText("Enter a decimal number : ");

        binlbl.setText("Enter a binary number :");

        decbtn.setText("Dec. to Bin.");
        decbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decbtnActionPerformed(evt);
            }
        });

        binbtn.setText("Bin. to Dec.");
        binbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binbtnActionPerformed(evt);
            }
        });

        decfinlbl.setText("...");

        binfinlbl.setText("...");

        hexttl.setText("Decimal and Hexadecimal");

        decilbl.setText("Enter a decimal number :");

        hexlbl.setText("Enter a hex number :");

        decibtn.setText("Dec. to Hex.");
        decibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decibtnActionPerformed(evt);
            }
        });

        hexbtn.setText("Hex. to Dec.");
        hexbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexbtnActionPerformed(evt);
            }
        });

        decifinlbl.setText("...");

        hexfinlbl.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(binttl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(hexttl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(declbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(decilbl)
                                .addComponent(binlbl))
                            .addComponent(hexlbl))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dectxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(decbtn)
                                .addGap(18, 18, 18)
                                .addComponent(decfinlbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(binbtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(hextxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hexbtn))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(decitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(decibtn)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(decifinlbl)
                                    .addComponent(binfinlbl)
                                    .addComponent(hexfinlbl))))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(binttl)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(declbl)
                    .addComponent(dectxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decbtn)
                    .addComponent(decfinlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binlbl)
                    .addComponent(bintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(binbtn)
                    .addComponent(binfinlbl))
                .addGap(30, 30, 30)
                .addComponent(hexttl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decilbl)
                    .addComponent(decitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decibtn)
                    .addComponent(decifinlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hexlbl)
                    .addComponent(hextxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hexbtn)
                    .addComponent(hexfinlbl))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void binbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binbtnActionPerformed
     String bin = bintxt.getText();
     int i = Integer.parseInt(bin,2);
     binfinlbl.setText("dec. " + i);
    }//GEN-LAST:event_binbtnActionPerformed

    private void decbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decbtnActionPerformed
       int dec = Integer.parseInt(dectxt.getText());
  
      decfinlbl.setText(Integer.toBinaryString(dec));
    
    }//GEN-LAST:event_decbtnActionPerformed

    private void decibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decibtnActionPerformed
    int deci = Integer.parseInt(decitxt.getText());
    decifinlbl.setText(Integer.toHexString(deci));
    }//GEN-LAST:event_decibtnActionPerformed

    private void hexbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexbtnActionPerformed
     String hex = hextxt.getText();
     int f = Integer.parseInt(hex, 16);
     hexfinlbl.setText("dec. "+f);
    }//GEN-LAST:event_hexbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(binaryhexfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(binaryhexfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(binaryhexfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(binaryhexfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new binaryhexfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton binbtn;
    private javax.swing.JLabel binfinlbl;
    private javax.swing.JLabel binlbl;
    private javax.swing.JLabel binttl;
    private javax.swing.JTextField bintxt;
    private javax.swing.JButton decbtn;
    private javax.swing.JLabel decfinlbl;
    private javax.swing.JButton decibtn;
    private javax.swing.JLabel decifinlbl;
    private javax.swing.JLabel decilbl;
    private javax.swing.JTextField decitxt;
    private javax.swing.JLabel declbl;
    private javax.swing.JTextField dectxt;
    private javax.swing.JButton hexbtn;
    private javax.swing.JLabel hexfinlbl;
    private javax.swing.JLabel hexlbl;
    private javax.swing.JLabel hexttl;
    private javax.swing.JTextField hextxt;
    // End of variables declaration//GEN-END:variables
}
